# Generated by Django 3.2 on 2021-04-20 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0009_rename_updated_timestamp_video_updated"),
        ("playlists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="videos.video",
            ),
        )
    ]
