# Generated by Django 3.2 on 2021-04-21 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0009_rename_updated_timestamp_video_updated"),
        ("playlists", "0003_auto_20210421_1153"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playlist_featured",
                to="videos.video",
            ),
        )
    ]
