# Generated by Django 3.2 on 2021-04-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("playlists", "0004_alter_playlist_video")]

    operations = [migrations.RemoveField(model_name="playlist", name="videos")]
