# Generated by Django 3.2 on 2021-04-24 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("playlists", "0006_auto_20210421_1611")]

    operations = [
        migrations.AddField(
            model_name="playlist", name="order", field=models.IntegerField(default=1)
        ),
        migrations.AddField(
            model_name="playlist",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="playlists.playlist",
            ),
        ),
    ]
