# Generated by Django 3.2 on 2021-04-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("playlists", "0010_alter_playlist_parent")]

    operations = [
        migrations.CreateModel(
            name="MovieProxy",
            fields=[],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("playlists.playlist",),
        )
    ]
