# Generated by Django 3.2 on 2021-04-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("categories", "0001_initial"), ("playlists", "0011_movieproxy")]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        )
    ]
