# Generated by Django 3.2 on 2021-05-03 02:12

from django.db import migrations, models
import django.db.models.deletion
import playlists.models


class Migration(migrations.Migration):

    dependencies = [("playlists", "0014_auto_20210503_0157")]

    operations = [
        migrations.AlterField(
            model_name="playlistrelated",
            name="related",
            field=models.ForeignKey(
                limit_choices_to=playlists.models.pr_limit_choices_to,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_item",
                to="playlists.playlist",
            ),
        )
    ]
