# Generated by Django 3.2 on 2021-04-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("videos", "0005_auto_20210420_1700")]

    operations = [
        migrations.AddField(
            model_name="video",
            name="state",
            field=models.CharField(
                choices=[("PU", "Publish"), ("DR", "Draft")], default="DR", max_length=2
            ),
        )
    ]
