# Generated by Django 3.2 on 2021-04-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("videos", "0007_video_publish_timestamp")]

    operations = [
        migrations.AddField(
            model_name="video",
            name="updated_timestamp",
            field=models.DateTimeField(auto_now=True),
        )
    ]
