# Generated by Django 3.2 on 2021-04-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("videos", "0008_video_updated_timestamp")]

    operations = [
        migrations.RenameField(
            model_name="video", old_name="updated_timestamp", new_name="updated"
        )
    ]
